# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-11-02 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191101_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='abstract',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
