# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-11-06 06:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='abstract',
            new_name='excerpt',
        ),
    ]
