# Generated by Django 2.2.5 on 2019-11-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191106_0631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_time', models.DateField()),
                ('intro', models.TextField()),
                ('body', models.TextField()),
                ('link', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('skills', models.ManyToManyField(to='blog.Tag')),
            ],
        ),
    ]
